#!/usr/bin/env bash

usage() {
	echo -e "\e[1;4mUsage:\e[0m $(basename $0) [options] <length>\n"
	echo -e "\e[1;4mOptions:\e[0m"
	echo -e "  \e[1m-c,--clip\e[0m  Copy the generated password to clipboard"
	echo -e "  \e[1m-h,--help\e[0m  Print this help message"
}

generate() {
	local charsets=(
		"abcdefghklmnopqrstuvwxyz"
		"ABCDEFGHKLMNOPQRSTUVWXYZ"
		"1234567890"
		"\!\"#$%&'()*+,-./\\:;?@[]^_\`{|}~ "
	)

	local pw=""

	for _ in $(seq 1 $1); do
		charset=${charsets[$(( RANDOM % ${#charsets[*]} ))]}
		pw="$pw${charset:$(( RANDOM % ${#charset} )):1}"
	done
	
	echo $pw
}

length=0
clip=0
pw=""

case $1 in
	-h|--help)
		usage
		exit 0
		;;
	-c|--clip)
		clip=1
		
		if [[ $2 -gt 0 ]]; then
			pw=$(generate $2)
		else
			echo "Length must be greater than zero" >&2
			exit 1
		fi
		;;
	*)
		pw=$(generate $1)
		;;
esac

if [[ $clip -eq 1 ]]; then
	wl-copy -o $pw
else
	echo $pw
fi

